# Generated by Django 3.0.4 on 2020-03-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('1st', 'Tutor'), ('2nd', 'Tutee'), ('3rd', 'Tutor and Tutee')], default='tutor', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('1st', 'First Year'), ('2nd', 'Second Year'), ('3rd', 'Third Year'), ('4th', 'Fourth Year')], default='1st', max_length=3),
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
